# Generated by Django 3.2.3 on 2021-05-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='PUser',
        ),
    ]
